### ISSUE TITLE
container map error creating block

### ISSUE THREAD

**Issue by sthaar** [etteerr/Matlab-Stimulus-Presenter#19]
Windows 10, MATLAB 2016b, PTB 3.0.13
When creating a new block, for example named "blok1" an error occurs: container map empty

this error does not appear in MATLAB 2015a

**Comment by sthaar** [comment]
Windows 10, MATLAB 2016b, PTB 3.0.13:
creating an experiment works fine but when running an experiment an error occurs using WaitSecs:
In error dialog: Error while generating experiment Event Wait reported init failure
In command window: Warning: Waitsecs not working. Function not included....(see pic)

![error_waitsecs](https://cloud.githubusercontent.com/assets/24313958/21117579/a2d198f8-c0ba-11e6-89b6-c0b67fd42d64.png)

**Comment by etteerr** [comment]
WaitSecs is a problem with the Psychtoolbox install. The error will be made more clear.
container map error will be looked into and will probably be catched.
