### ISSUE TITLE
experiment gets stuck

### ISSUE THREAD

**Issue by sthaar** [etteerr/Matlab-Stimulus-Presenter#25]
Experiment gets stuck after transition to new block?? picture is shown, wait 10sec, next picture in new block does not appear, experiment does not proceed.

Error using imread (line 362)
Unable to determine the file format.

Error in runTrial (line 181)
end

Error in runExperiment (line 85)
            feedback = runTrial(trial,hWindow,runTrialMode);

Error in ExperimentStarter>StartExperiment_Callback (line 210)
    Data = runExperiment(ExperimentData,hW);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in ExperimentStarter (line 56)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ExperimentStarter('StartExperiment_Callback',hObject,eventdata,guidata(hObject)) 
Error using start>buttonStart_Callback (line 113)
Error while evaluating UIControl Callback

**Comment by etteerr** [comment]
This is a data input error. Matab is unable to open a image out of a set.
